### ISSUE TITLE
Download dependencies error on Raspberry Zero W

### ISSUE THREAD

**Issue by namero999** [synesthesiam/rhasspy-hassio-addon#189] opened 2020-03-06 21:28 UTC
During the execution of the `download-dependencies.sh` script, I got this error.

```
curl: (22) The requested URL returned error: 404 Not Found
Can't download https://github.com/synesthesiam/kaldi-docker/releases/download/v1.0/kaldi_armv6l.tar.gz
```

Probably the script should fallback to `armhf` as arch for the zero.

**Comment by Tooa** [comment] 2020-03-08 09:35
The problem is that there is no tag `v1.0` in the `kaldi-docker` repo ([reference](https://github.com/synesthesiam/docker-kaldi/releases)). The correct file is probably [` kaldi-2020-armhf.tar.gz`](https://github.com/synesthesiam/docker-kaldi/releases/download/v2020.1/kaldi-2020-armhf.tar.gz)

**Comment by namero999** [comment] 2020-03-11 11:41
Yes, I ended up manually wget-ing it and placing it into `~/config/rhasspy/profiles/en/download`

**Comment by synesthesiam** [comment] 2020-03-28 19:55
OK, should be fixed in `master`

**Closed as completed** 2020-03-28 19:55 UTC
