### ISSUE TITLE
ERROR: rhasspy-nlu 0.1.4.1 has requirement networkx==2.3, but you'll have networkx 2.4 which is incompatible.

### ISSUE THREAD

**Issue by vicvega83** [synesthesiam/rhasspy-hassio-addon#159] opened 2020-01-14 16:41 UTC
Hi, I'm installing it following the instructions for virtual environment, on a Raspberry pi 3. I'm not aware of anything that should have installed networkx 2.4, isn't the virtualenv going to isolate from the rest of the software installed anyway ?
thanks :)

**Comment by koenvervloesem** [comment] 2020-01-14 16:56
This should be fixed soon when a new package of rhasspy-nlu has been published, see https://github.com/rhasspy/rhasspy-nlu/issues/5

The problem is that two packages in this virtual environment want a different version of networkx.

But in practice I don't think that this error will be an issue. It has been there for a while and Rhasspy just works here. So you can ignore it for now.

**Comment by synesthesiam** [comment] 2020-01-15 03:25
@koenvervloesem is correct. This will be fixed with `rhasspy-nlu` 0.1.5 is published (probably this week).

**Closed as completed by synesthesiam** 2020-01-15 03:25 UTC
