### ISSUE TITLE
Send intents to Home Assistant link broken

### ISSUE THREAD

**Issue by Tooa** [synesthesiam/rhasspy-hassio-addon#177] opened 2020-02-09 20:37 UTC
# Problem statement

The link in the web interface `Settings -> Intent Handling` [here](https://github.com/synesthesiam/rhasspy/blob/3eb4368b37ca86dad4ab7aa0c7cd4b7e96d32722/src/components/profile/IntentHandling.vue#L89) is broken i.e. returns `Page Not Found`.

# Details

* Rhasspy version: 2.4.18

**Comment by Romkabouter** [comment] 2020-03-15 08:14
Please confirm if this is fixed in 2.4.19.

I cannot reproduce this issue

**Comment by Tooa** [comment] 2020-03-22 07:47
Version `2.4.19` still references a broken link:

https://github.com/synesthesiam/rhasspy/blob/v2.4.19/src/components/profile/IntentHandling.vue#L89

**Comment by synesthesiam** [comment] 2020-04-10 17:33
Will be fixed in 2.4.20

**Closed as completed by synesthesiam** 2020-04-10 17:33 UTC
Labels: in progress
